### ISSUE TITLE
sails lift not starting gulp

### ISSUE THREAD

**Issue by tom-s** [Karnith/sails-generate-frontend-gulp#18]
Hi Karnith,

First thanks for your great work. I have an issue with sails lift not triggering gulp at all. I have to launch gulp in the terminal to get the tasks executed (which works). What is supposed to make gulp trigger on sails lifting ?

**Comment by Karnith** [comment]
Hi,

Due to changes in sails you need to delete the node_modules folder in the project, then do npm install. I'm in the process of changing thing to flow better.


-------- Original message --------

**Comment by tom-s** [comment]
HI,

Thanks for answering so quickly. Unfortunately I still have the same issue after following your instructions. I get the following when doing sails lift, but gulp is not started

```
info: Starting app...
info: Gruntfile could not be found.
info: (no grunt tasks will be run.)
```

I have the following .sailsrc and installed the corresponding packages globally.
```
{
  "generators": {
    "modules": {
      "new": "sails-generate-new-gulp",
      "frontend": "sails-generate-frontend-gulp",
      "backend": "sails-generate-backend-gulp",
      "gulpfile": "sails-generate-gulpfile"
    }
  }
}
```

Any idea of how Ii could debug / solve this problem ?

**Comment by Karnith** [comment]
This is because of the .sailsrc in the project I think…

Look for it in the root project foler and see if it matches the following:

{
  "hooks": {
    "grunt": false
  },
  "generators": {
    "modules": {
      "bower": "sails-generate-bower-gulp",
      "angular": "sails-generate-angular-gws"
    }
  }
}

The “grunt”:false is what tells sails  not to use grunt so that the above error isn’t present.

Can you share with me the process of how your creating a project and the generators you have installed. I just recently tested the generators and they still work, I’m wondering if you are missing one of them.

**Comment by tom-s** [comment]
Hi,

I got that the grunt warning was coming from the grunt hook not being 
disabled. But even though I disabled it, what is telling sails to use 
gulp ? That's the bit I didn't get at all. I've copied my .sailsrc in 
the former message, it looks like this


{

"generators": {

"modules": {

"new": "sails-generate-new-gulp",

"frontend": "sails-generate-frontend-gulp",

"backend": "sails-generate-backend-gulp",

"gulpfile": "sails-generate-gulpfile"

}

**Comment by Karnith** [comment]
There is a user hook that tells sails to use gulp and is at api => hooks => gulp.

There should be two .sailsrc, one in the location to where you want to create your project and will be running the sails new command (e.g root/nodeProjects/.sailsrc or for windows C:\nodeProjects\.sailsrc) the second will be in the actual project folder where app.js and gulpfile.js are. Can you post the .sailsrc of the one in the project folder please?

Thx

**Comment by tom-s** [comment]
Hi,

It turns out the api hook was missing. I just used "sails generate frontend" command line (wrongly) thinking it would do all the job, but it turns out I had to create a new project with "sails-generate-new-gulp" to have it working. Anyway thanks very much for your help and your work.

**Comment by Karnith** [comment]
Ok, but if you have your external project .sailsrc configured correctly all you would need to use is sails new <project name>. The external .sailsrc file overrides the standard sails new command by changing the default project generators with the ones I created.

Project hierarchy should be as follows:

<drive>
|_ .sailsrc
|_ newly created project folder from sails new command
    |_ project .sailsrc and other sails files/folders

Thanks,
Karnith


-------- Original message --------
